<a href="https://colab.research.google.com/github/Nick-FF/NLP/blob/Less2/word2vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Embeddings и векторные представления текста в NLP

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from itertools import chain
import pandas as pd
import numpy as np

In [ ]:
# !wget https://github.com/ods-ai-ml4sg/proj_news_viz/releases/download/data/gazeta.csv.gz

In [ ]:
# # пример работы с ним 
# from corus import load_ods_gazeta

In [ ]:

# path = 'gazeta.csv.gz'
# records = load_ods_gazeta(path)
# next(records)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Загрузим данные с прошлого урока

In [ ]:
# read from pickle file data  
tweets = pd.read_pickle('twitter.pkl')
tweets.head(5)

,id,label,tweet,tweet_token,tweet_tokenize,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,1,0.0,@user when a father is dysfunctional and is s...,user when father is dysfunctional and is so se...,"[user, when, father, is, dysfunctional, and, i...","[user, father, dysfunctional, selfish, drags, ...","[user, father, dysfunct, selfish, drag, kid, d...","[user, father, dysfunct, selfish, drag, kid, d..."
1,2,0.0,@user @user thanks for #lyft credit i can't us...,user user thanks for lyft credit can use cause...,"[user, user, thanks, for, lyft, credit, can, u...","[user, user, thanks, lyft, credit, use, cause,...","[user, user, thank, lyft, credit, use, caus, o...","[user, user, thank, lyft, credit, use, caus, o..."
2,3,0.0,bihday your majesty,bihday your majesty,"[bihday, your, majesty]","[bihday, majesty]","[bihday, majesti]","[bihday, majesti]"
3,4,0.0,#model i love u take with u all the time in ...,model love take with all the time in ur,"[model, love, take, with, all, the, time, in, ur]","[model, love, take, time, ur]","[model, love, take, time, ur]","[model, love, take, time, ur]"
4,5,0.0,factsguide: society now #motivation,factsguide society now motivation,"[factsguide, society, now, motivation]","[factsguide, society, motivation]","[factsguid, societi, motiv]","[factsguid, societi, motiv]"

#### Создание признакового простанства с помощью библиотеки sklearn

In [ ]:
# bag_of_words for stemming data of tweeter
count_vectorizer_stemmed = CountVectorizer(ngram_range=(1, 1),
                                   analyzer='word',
                                   max_df=0.9,
                                   stop_words="english",
                                   max_features=1000,
                                   binary=False,)

count_vectorizer_stemmed.fit(list(chain.from_iterable(tweets['tweet_stemmed'].tolist())))
bag_of_words_stemmed = count_vectorizer_stemmed.fit_transform(tweets['tweet_stemmed'].apply(lambda x: ' '.join([word for word in x])))
feature_names = count_vectorizer_stemmed.get_feature_names()
df_stemmed = pd.DataFrame(bag_of_words_stemmed.toarray(), columns = feature_names)
df_stemmed

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,yeah,year,yesterday,yo,yoga,york,young,youtub,yr,yummi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38794,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38795,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38796,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38797,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38798,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
#find any word in first tweet
in_dict = [tweet for tweet in tweets['tweet_stemmed'][0] if tweet in count_vectorizer_stemmed.get_feature_names()]
in_dict

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['user', 'father', 'kid', 'run']

In [ ]:
# check if word 'father' get in matrix in first row
df_stemmed['father'][0]

1

yes, this it

In [ ]:
# bag_of_words for lemmitized data of tweeter
count_vectorizer_lemmitized = CountVectorizer(ngram_range=(1, 1),
                                   analyzer='word',
                                   max_df=0.9,
                                   stop_words="english",
                                   max_features=1000,
                                   binary=False,)

count_vectorizer_lemmitized.fit(list(chain.from_iterable(tweets['tweet_lemmatized'].tolist())))
bag_of_words_lemmitized = count_vectorizer_lemmitized.fit_transform(tweets['tweet_lemmatized'].apply(lambda x: ' '.join([word for word in x])))
feature_names = count_vectorizer_lemmitized.get_feature_names()
df_lemmitized = pd.DataFrame(bag_of_words_lemmitized.toarray(), columns = feature_names)
df_lemmitized

,abl,absolut,accept,account,act,action,activ,actor,actual,ad,...,yeah,year,yesterday,yo,yoga,york,young,youtub,yr,yummi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38794,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38795,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38796,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38797,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38798,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# elso checking matrix 
df_lemmitized['father'][0]

1

In [ ]:
tfidf_vectorizer_stemmed = TfidfVectorizer(max_df=0.9, max_features=1000, stop_words='english')
tfidf_vectorizer_stemmed.fit(list(chain.from_iterable(tweets['tweet_stemmed'].tolist())))

values_stemmed_idf = tfidf_vectorizer_stemmed.fit_transform(tweets['tweet_stemmed'].apply(lambda x: ' '.join([word for word in x])))
feature_names_stemmed_idf = tfidf_vectorizer_stemmed.get_feature_names()
df_stemmed_idf = pd.DataFrame(values_stemmed_idf.toarray(), columns = feature_names_stemmed_idf)
df_stemmed_idf

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,abl,absolut,accept,account,act,action,actor,actual,ad,adapt,...,yeah,year,yesterday,yo,yoga,york,young,youtub,yr,yummi
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38794,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38795,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38796,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38797,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38798,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# checking own matrix
df_stemmed_idf['father'][0]

0.4770956196892355

In [ ]:
tfidf_vectorizer_lemmitized = TfidfVectorizer(max_df=0.9, max_features=1000, stop_words='english')
tfidf_vectorizer_lemmitized.fit(list(chain.from_iterable(tweets['tweet_lemmatized'].tolist())))

values_lemmitized_idf = tfidf_vectorizer_lemmitized.fit_transform(tweets['tweet_lemmatized'].apply(lambda x: ' '.join([word for word in x])))
feature_names_lemmitized_idf = tfidf_vectorizer_lemmitized.get_feature_names()
df_lemmitized_idf = pd.DataFrame(values_lemmitized_idf.toarray(), columns = feature_names_lemmitized_idf)
df_lemmitized_idf

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,abl,absolut,accept,account,act,action,activ,actor,actual,ad,...,yeah,year,yesterday,yo,yoga,york,young,youtub,yr,yummi
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38794,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38795,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38796,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38797,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38798,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df_stemmed_idf['father'][0]

0.4770956196892355

### Работа векторным представлением слов с помощью моделей gensim

познакомимся с моделью и немного поиграем с примерами

In [ ]:
import gensim.downloader as api
# most famous example ))
word_vectors = api.load('glove-wiki-gigaword-100')
result = word_vectors.most_similar(positive=['woman', 'king'], negative=['man'])
print(result)

[==================================================] 100.0% 128.1/128.1MB downloaded
[('queen', 0.7698541283607483), ('monarch', 0.6843380928039551), ('throne', 0.6755735874176025), ('daughter', 0.6594556570053101), ('princess', 0.6520534753799438), ('prince', 0.6517034769058228), ('elizabeth', 0.6464517712593079), ('mother', 0.6311717629432678), ('emperor', 0.6106470823287964), ('wife', 0.6098655462265015)]

In [ ]:
result = word_vectors.similarity('he', 'she')
print(result)

0.86484975

In [ ]:
result = word_vectors.similar_by_word('ignition', topn=3)
result

[('exhaust', 0.6132949590682983),
 ('valve', 0.60724937915802),
 ('interlock', 0.6046040058135986)]

In [ ]:
result = word_vectors.similar_by_word('starship', topn=3)
result

[('cruiser', 0.5517100691795349),
 ('starfleet', 0.5381706953048706),
 ('voyager', 0.536540150642395)]

In [ ]:
result = word_vectors.similar_by_word('sputnik', topn=3)
result

[('vostok', 0.5843233466148376),
 ('apstar', 0.5680071711540222),
 ('intelsat', 0.5594972372055054)]

In [ ]:
result = word_vectors.similar_by_word('bacteria', topn=3)
result

[('bacterium', 0.8015254735946655),
 ('microbes', 0.7992997169494629),
 ('microorganisms', 0.7968827486038208)]

### Обучение модели Word2Vec

In [ ]:
from gensim.models import Word2Vec
model_tweets = Word2Vec(size=200,
                       window = 5,
                       min_count = 2,
                       sg = 1,
                       hs = 0,
                       negative = 10,
                       workers = 32,
                       seed = 34)

TypeError: ignored

In [ ]:
# create vocabular
model_tweets.build_vocab(tweets['tweet_token'])

WARNING:gensim.models.word2vec:Each 'sentences' item should be a list of words (usually unicode strings). First item here is instead plain <class 'str'>.

In [ ]:
model_tweets.train(tweets['tweet_token'], total_examples=len(tweets['tweet_token']), epochs=20)

(9443118, 55081300)

In [ ]:
# find similary word for word 'dinner'
result = model_tweets.wv.most_similar(positive=['user'])
print(result)

KeyError: ignored

In [ ]:
# find similary word for word 'trump'
result = model_tweets.wv.most_similar(positive=['trump'])
print(result)

KeyError: ignored

In [ ]:
# get vector for word 'food'
result = model_tweets.wv.get_vector('food')
print(result)

KeyError: ignored

In [ ]:
result.shape

AttributeError: ignored

In [ ]:
# same way
result = model_tweets.wv['food']
print(result)

KeyError: ignored

In [ ]:
vector_w2v = np.zeros((len(tweets['tweet_token']), 200))
for i, tweet in enumerate(tweets['tweet_token']):
    for t in tweet:
        vector_w2v[i] += model_tweets.wv[t]
    l = len(tweet)
    if l > 0:
        vector_w2v[i] /= l

vector_w2v